name: Terraform Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590184067731:role/oidc-role
          aws-region: us-east-1

      - name: Verify AWS
        run: |
          aws sts get-caller-identity

       # 4. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 5. Check Terraform version
      - name: Terraform Version
        run: terraform version

      # 6. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 7. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 8. Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # 9. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
